// <auto-generated />
using System;
using InfraPlayground.Auth.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraPlayground.Auth.Persistence.Migrations
{
    [DbContext(typeof(InfraPlaygroundAuthDbContext))]
    partial class InfraPlaygroundAuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfraPlayground.Auth.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6a6fd4f-8a61-47b2-87e4-c7d8f934c1d1"),
                            Description = "Yazılım geliştirmede okunabilirlik ve sürdürülebilirlik prensipleri.",
                            Isbn = "9780132350884",
                            Price = 42.50m,
                            PublicationYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("22fdfd36-83fd-45b6-aa09-c19f453f4fb2"),
                            Description = "Karmaşık domain problemleri için modelleme yaklaşımı.",
                            Isbn = "9780321125217",
                            Price = 55.00m,
                            PublicationYear = 2003,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = new Guid("bb3dcb8d-f4c0-4bb2-87a4-b3db9fd11b7f"),
                            Description = "Pratik yazılım geliştirme alışkanlıkları ve mühendislik bakışı.",
                            Isbn = "9780201616224",
                            Price = 39.90m,
                            PublicationYear = 1999,
                            Title = "The Pragmatic Programmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
